config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  get "faq", to: "pages#faq"
  get "contact", to: "pages#contact"
  get "buy", to: "pages#buy"

  get "demo", to: "pages#components"

  get 'components', to: 'component#index', as: "component_index"
  get 'components/:id', to: 'component#show', as: "component"
  get 'component-item/:type/:id', controller: "component", action: "component_item", as: "single_component"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/component_controller.rb
class ComponentController < ApplicationController

  layout 'component'

  def index
    fetch_patterns(["atoms", "molecules", "organisms", "pages", "templates"])
  end

  def show
    fetch_patterns([params[:id]])
    @pattern = params[:id].capitalize
  end

  def component_item
    @partial = "component/#{params[:type]}/#{params[:id]}"
    @sourcepartial = File.open("#{Rails.root}/app/views/component/#{params[:type]}/_#{params[:id]}.html.erb").read
    @pattern = params[:id].capitalize
  end

  private

  def fetch_patterns(groups)
    @pattern_groups = groups
    @patterns = {}
    @pattern_groups.each do |dir|
      group = @patterns[dir] = []
      fetch_files(dir).sort.each do |method|
        string = method.split("/").last
        string[0] = ""
        group << string
      end
    end
    @patterns
  end

  def fetch_files(dir)
    Dir.glob("#{Rails.root}/app/views/component/#{dir}/*.erb")
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/component_helper.rb
module ComponentHelper
  def filename( string )
    string.split('.').first
  end

  def pattern_id( key, pattern )
    "#{key}_#{filename(pattern)}".downcase
  end
end

app/views/component/_pattern.html.erb
<%- @pattern_groups.each do |key| -%>
  <%- if @patterns[key].present? %>
    <%- @patterns[key].each do |pattern| -%>

      <p><%= link_to "#{key.capitalize}", component_path(key) if context %> <%= "#{filename(pattern).tr("_", " ").capitalize}" %></p>
      <div class="pattern" id="pattern_<%= pattern_id( key, pattern ) %>">
        <div class="pattern-code">
          <input type="checkbox" id="view_html_<%= pattern_id( key, pattern ) %>"><label for="view_html_<%= pattern_id( key, pattern ) %>">View Source</labeL>
          <%= link_to "&#x279D;".html_safe, single_component_path({ :type=>key, :id=>pattern.gsub(".erb","") }), :class => "pattern-anchor", title: "Direct link to this component" %>

          <code class="language-markup"><%= File.open("#{Rails.root}/app/views/component/#{key}/_#{pattern}").read %></code>
        </div>
        <div class="pattern-preview">
          <div class="pattern-layout">
            <%= render partial: "component/#{key}/#{pattern}" %>
          </div>
        </div>
      </div>

    <%- end -%>
  <%- end -%>
<%- end -%>

app/views/component/atoms/_buttons.html.erb
<button class="btn btn-primary">Primary Button</button>
<button class="btn btn-primary-outline">Primary Button Outlined</button>

app/views/component/atoms/_headings.html.erb
<h1>Heading 1</h1>
<h2>Heading 2</h2>
<h3>Heading 3</h3>

<p class="headline">Headline</p>
<p class="sub-headline">Sub Headline</p>

app/views/component/component_item.html.erb
<div class="component-header">
  <h1>Component Library: <%= @pattern %></h1>
</div>

<div><span class="sg-pattern-name"><%= @pattern %></span></div>
<div class="pattern">
  <div class="pattern-code">
    <input type="checkbox" id="view_html"><label for="view_html">View Source</labeL>
    <code class="language-markup"><%= @sourcepartial %></code>
  </div>
  <div class="pattern-preview">
    <div class="pattern-layout">
      <%= render :partial => @partial %>
    </div><!-- .pattern-layout -->
  </div><!-- .pattern-preview -->
</div><!-- .pattern -->

app/views/component/index.html.erb
<div class="component-header">
  <h1>Component Library: All Components</h1>
</div>

<div class="patterns">
<%= render partial: "pattern", locals: { context: true }  %>
</div>

app/views/component/molecules/_hero.html.erb
<div class="hero">
  <h2 class="headline hero-headline">
    Need a barcode for your business?
  </h2>
  <h3 class="sub-headline hero-sub-headline">
    We've got you covered with the best prices and customer service in Israel.
  </h3>
</div>

app/views/component/molecules/_navbar_brand.html.erb
<a class="navbar-brand navbar-link" href="#"><%= image_tag "logo.png", class: "navbar-brand-image" %><span class="navbar-brand-text"><strong>BARCODES</strong>ISRAEL</span></a>

app/views/component/molecules/_testimonials.html.erb
<div class="testimonials row">
  <div class="col-sm-4">
    <blockquote class="testimonial">
      <p>Super awesome service! You have changed my life, thank you so much Barcodes Israel</p>
      <cite>Bob Sawyer</cite>
    </blockquote>
  </div>

  <div class="col-sm-4">
    <blockquote class="testimonial">
      <p>Super awesome service! You have changed my life, thank you so much Barcodes Israel</p>
      <cite>Bob Sawyer</cite>
    </blockquote>
  </div>

  <div class="col-sm-4">
    <blockquote class="testimonial">
      <p>Super awesome service! You have changed my life, thank you so much Barcodes Israel</p>
      <cite>Bob Sawyer</cite>
    </blockquote>
  </div>
</div>

app/views/component/molecules/_why_us.html.erb
<div class="why-us">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h2 class="headline why-us-headline">Why buy from us?</h2>
      </div>
      <div class="col-sm-6">
        <div class="why-us-about-us">
          <p>
            We are Kenya’s largest and most trusted online barcode
store, and our barcodes are accepted by the vast of majority
of retailers nationwide. We also provide for quick, hassle-free
and secure payment facilities through PAYFAST in order to
give you, the customer, complete peace of mind when
making a purchase.
          </p>
          <p>Any questions? Please
            <a href="#">contact us</a>
          </p>
        </div>
      </div>

      <div class="col-sm-6">
        <ul class="why-us-item-list">
          <li class="why-us-item">
            <span class="why-us-icon glyphicon glyphicon-ok-sign"></span>
            <span>Instant and secure payment</span>
          </li>
          <li class="why-us-item"><i class="why-us-icon glyphicon glyphicon-ok-sign"></i>Unique and Authentic GS1 Barcodes</li>
          <li class="why-us-item"><i class="why-us-icon glyphicon glyphicon-ok-sign"></i>1 hour delivery time during working hours</li>
          <li class="why-us-item"><i class="why-us-icon glyphicon glyphicon-ok-sign"></i>No hidden costs or renewal fees</li>
          <li class="why-us-item"><i class="why-us-icon glyphicon glyphicon-ok-sign"></i>Highest retailer acceptance rates in Kenya</li>
          <li class="why-us-item"><i class="why-us-icon glyphicon glyphicon-ok-sign"></i>High quality barcode images included</li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/component/organisms/_footer.erb
<footer>
  <nav class="navbar footer-navbar">
    <div class="navbar-padding">
      <div class="container footer-container">
        <ul class="nav navbar-nav footer-navbar-nav">
          <li><a class="navbar-link" href="#">Home</a></li>
          <li><a class="navbar-link" href="#">FAQ</a></li>
          <li><a class="navbar-link" href="#">Contact Us</a></li>
          <li><a class="navbar-link" href="#">Buy Barcodes</a></li>
        </ul>
      </div>
    </div>
  </nav>
</footer>

app/views/component/organisms/_header.html.erb
<div class="header">
  <nav class="navbar navbar-fixed-top">
    <div class="navbar-padding">
      <div class="container">

        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a class="navbar-brand navbar-link" href="#">
            <%= image_tag "logo.png", class: "navbar-brand-image" %>
            <span class="navbar-brand-text"><strong>BARCODES</strong>ISRAEL</span>
          </a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a class="navbar-link" href="#">Home</a></li>
            <li><a class="navbar-link" href="#">FAQ</a></li>
            <li><a class="navbar-link" href="#">Contact Us</a></li>
            <li class="separator"></li>
            <li><a class="btn btn-primary-outline navbar-link" href="#">Buy Barcodes</a></li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</div>

app/views/component/pages/_buy_barcodes.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-7">
      <h1 class="headline headline-buy">Purchase Your Barcodes Online in Minutes!</h1>
      <p>Remember, if you're looking to buy barcodes online, we offer <strong>1-hour email delivery</strong> on all orders and have the guaranteed lowest prices in SA! We can supply you with a same-hour quote for any quantity of barcodes required. All barcodes are pre-approved and verified for use in South African retailers, and all barcodes are fully Gs1-authorised. Please see below for more details of what you will receive when you buy your barcodes online from us.</p>

      <div class="panel panel-default">
        <table class="table table-buy table-bordered table-striped">
          <thead>
            <tr>
              <th class="table-header-buy">Quantity</th>
              <th class="table-header-buy">Price</th>
              <th class="table-header-buy"></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>Ksh 1600.00</td>
              <td class="table-buy-column"><button class="btn btn-primary btn-wide">Buy Now</button></td>
            </tr>
            <tr>
              <td>2</td>
              <td>Ksh 2800.00</td>
              <td class="table-buy-column"><button class="btn btn-primary btn-wide">Buy Now</button></td>
            </tr>
            <tr>
              <td>5</td>
              <td>Ksh 5000.00</td>
              <td class="table-buy-column"><button class="btn btn-primary btn-wide">Buy Now</button></td>
            </tr>
            <tr>
              <td>10</td>
              <td>Ksh 9300.00</td>
              <td class="table-buy-column"><button class="btn btn-primary btn-wide">Buy Now</button></td>
            </tr>
            <tr>
              <td>20</td>
              <td>Ksh 17400.00</td>
              <td class="table-buy-column"><button class="btn btn-primary btn-wide">Buy Now</button></td>
            </tr>
            <tr>
              <td>50</td>
              <td>Ksh 31000.00</td>
              <td class="table-buy-column"><button class="btn btn-primary btn-wide">Buy Now</button></td>
            </tr>
            <tr>
              <td>100</td>
              <td>Ksh 55000.00</td>
              <td class="table-buy-column"><button class="btn btn-primary btn-wide">Buy Now</button></td>
            </tr>
            <tr>
              <td>200</td>
              <td>Ksh 100000.00</td>
              <td class="table-buy-column"><button class="btn btn-primary btn-wide">Buy Now</button></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="col-sm-5">
      <div class="panel panel-default payment-icons-panel">
        <%= image_tag "secure-payment.png", class: "img-responsive center-block" %>
      </div>
      <div class="panel panel-default panel-whats-included">
        <div class="panel-heading">
          <h2 class="headline headline-buy">What's Included:</h3>
        </div>


        <div class="included-item">
          <h3 class="included-item-title">
            Both EAN and UPC Barcode Formats
          </h3>
          <p>(For local and international use)</p>
          <%= image_tag "ean-and-upc-barcodes.png", class: "img-responsive center-block included-item-image" %>
        </div>

        <div class="included-item">
          <h3 class="included-item-title">
            High Resolution Barcode Images
          </h3>
          <%= image_tag "image-formats.png", class: "img-responsive center-block included-item-image" %>
        </div>

        <div class="included-item">
          <h3 class="included-item-title">
            Certificate of Authenticity and Business Invoice
          </h3>
          <%= image_tag "invoice-and-certificate.png", class: "img-responsive center-block included-item-image" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/component/pages/_contact_us.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1 class="headline headline-contact-us">Contact Us</h1>
    </div>
    <div class="col-sm-6 contact-form">
      <h1 class="sub-headline headline-contact-us">Send Us a Message</h1>
      <p>We would love to hear form you. Please don't hesistate to contact us if you have any questions</p>
      <form>
        <div class="row">
          <div class="col-sm-6">
            <div class="form-group">
              <label for="name">Name</label>
              <input required="true" type="text" class="form-control" id="name" placeholder="Name">
            </div>
          </div>

          <div class="col-sm-6">
            <div class="form-group">
              <label for="email">Email address</label>
              <input required="true" type="email" class="form-control" id="email" placeholder="Email">
            </div>
          </div>
        </div>

        <div class="form-group">
          <label for="message">Message</label>
          <textarea required="true" class="form-control" id="message" rows="10"></textarea>
        </div>

        <button class="btn btn-primary btn-contact-us" type="submit">Send</button>
      </form>
    </div>
    <div class="col-sm-5">


      <p><strong>Email:</strong> <br><a href="#">support@barcodes.co.il</a></p>
      <p><strong>Phone:</strong><br>+27827768946</p>
      <p><strong>Address:</strong> <br>1 Mayfair Court <br> Mount Road <br> Kenilworth <br> 7708</p>

      <iframe frameborder="0" scrolling="no" marginheight="0" marginwidth="0"width="100%" height="250px" src="https://maps.google.com/maps?hl=en&q=Wessels Road, Kenilworth, Cape Town&ie=UTF8&t=m&z=16&iwloc=B&output=embed"></iframe>
    </div>
  </div>
</div>

app/views/component/pages/_faq.html.erb
<div class="container">
  <h1 class="headline headline-faq">Frequently Asked Questions</h1>

  <ul class="faq-summary-list">
    <li><a class="faq-summary-list-link" href="#">What is a Barcode?</a></li>
    <li><a class="faq-summary-list-link" href="#">How are Barcodes used?</a></li>
    <li><a class="faq-summary-list-link" href="#">How many Barcode numbers do I need?</a></li>
  </ul>

  <div class="faq-answer">
    <h2 class="sub-headline sub-headline-faq">What is a Barcode?</h2>
    <p>Barcodes, also referred to as UPC and EAN codes, are simply unique numbered-codes (12 or 13 digits in length) that, when logged with a retailer, allow for the tracking and monitoring of a product within their digital inventories.</p>
  </div>

  <div class="faq-answer">
    <h2 class="sub-headline sub-headline-faq">How are Barcodes used?</h2>
    <p>When you have a product to sell, you will invariably take it to a retailer like Pick n’ Pay or Musica. They will then have to manually enter your product information into their system. At this stage they will also log your unique EAN-code into their inventory. Following this, every time that your barcode gets scanned at the teller, your personal account will be credited with a sale. The barcode simply connects the one to the other.</p>
  </div>

  <div class="faq-answer">
    <h2 class="sub-headline sub-headline-faq">How many Barcode numbers do I need?</h2>
    <p>You need a barcode for each different size, flavour, colour and variation of the product that you intend to sell. So, for instance, if you are selling yellow and green cushions in 2 different sizes you will require 4 separate barcodes. This is so that the retailer can keep track of the exact sales data of each of the 4 products and react accordingly. Therefore if your smaller-green cushions are selling at a faster rate than the others, they can order more of those to keep up with demand.</p>
  </div>
</div>

app/views/component/show.html.erb
<div class="component-header">
  <h1>Component Library: <%= @pattern %></h1>
  <p><a href="/components">View all</a></p>
</div>

<div class="patterns">
<%= render partial: "pattern", locals: { context: false } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Barcodes Israel</title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<style>
body {
direction:rtl;
} 
</style>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
    <nav class="navbar navbar-fixed-top">
      <div class="navbar-padding">
        <div class="container">

          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header navbar-right">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-nav">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

            <%= link_to root_path, class: "navbar-brand navbar-link" do %>
              <%= image_tag "logo.png", class: "navbar-brand-image" %>
              <span class="navbar-brand-text"><strong>ברקודים </strong>​ישראל</span>
            <% end %>
          </div>

          <div class="collapse navbar-collapse" id="header-nav">
            <ul class="nav navbar-nav navbar-left">
              <li>
                <%= link_to "דף הבית", root_path, class: "navbar-link" %>
              </li>
              <li>
                <%= link_to "שאלות נפוצות", faq_path, class: "navbar-link" %>
              </li>
              <li>
                <%= link_to "צור קשר", contact_path, class: "navbar-link" %>
              </li>
              <li class="separator"></li>
              <li>
                <%= link_to "רכישת הברקודים שלך", buy_path, class: "btn btn-primary-outline navbar-link" %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
  </div>

  <%= yield %>

  <footer>
    <nav class="navbar footer-navbar">
      <div class="footer-navbar-padding">
        <div class="container footer-container">
          <ul class="nav navbar-nav footer-navbar-nav">
            <li>
              <%= link_to "דף הבית", root_path, class: "navbar-link" %>
            </li>
            <li>
              <%= link_to "שאלות נפוצות", faq_path, class: "navbar-link" %>
            </li>
            <li>
              <%= link_to "צור קשר", contact_path, class: "navbar-link" %>
            </li>
            <li>
              <%= link_to "רכישת הברקודים שלך", buy_path, class: "navbar-link" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </footer>
</body>
</html>

app/views/layouts/component.html.erb
<!DOCTYPE html>
<!--[if lte IE 9]> <html class="ie"> <![endif]-->
<!--[if gt IE 9]>  <html> <![endif]-->
<!--[if !IE]><!--> <html>             <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Component Library</title>

  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous"> -->


  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= stylesheet_link_tag    'component', media: 'all' %>
  <meta name="viewport" content="width=device-width">
  <%= csrf_meta_tags %>
</head>
<body class="no-js">
  <script>(function(e,t,n){var r=e.querySelectorAll("body")[0];r.className=r.className.replace(/(^|\s)no-js(\s|$)/,"$1js$2")})(document,window,0);</script>

<%= yield %>

  <%= javascript_include_tag 'application' %>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  <%= javascript_include_tag 'vendor/prism' %>
  <script type="text/javascript">var switchTo5x=true;</script>
  <script type="text/javascript" src="https://ws.sharethis.com/button/buttons.js"></script>
  <script type="text/javascript">stLight.options({publisher: "568018b5-27e6-4aa2-afc6-036e03b3ddc3", servicePopup: true});</script>
</body>
</html>

app/views/pages/buy.html.erb
<div class="container buy-container">
  <div class="row">
    <div class="col-sm-7">
      <h1 class="headline headline-buy"><%= I18n.t "buy-barcodes.headline" %></h1>
      <% I18n.t("buy-barcodes.paragraphs").each do |paragraph| %>
        <p><%= paragraph %></p>
      <% end %>

      <div class="panel panel-default">
        <table class="table table-buy table-bordered table-striped">
          <thead>
            <tr>
              <th class="table-header-buy">כמות</th>
              <th class="table-header-buy">מחיר</th>
              <th class="table-header-buy"></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td><span dir="ltr">75.00</span> ש"ח</td>
              <td class="table-buy-column"><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="2XG8KXQP7G7DN">
<input type="image" src="https://www.paypalobjects.com/he_IL/i/btn/btn_buynow_LG.gif" border="0" name="submit" alt="PayPal - הדרך הקלה והבטוחה יותר לשלם באינטרנט!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>
</td>
            </tr>
            <tr>
              <td>5</td>
              <td><span dir="ltr">275.00</span> ש"ח</td>
              <td class="table-buy-column"><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="CRFK3D66YMEHA">
<input type="image" src="https://www.paypalobjects.com/he_IL/i/btn/btn_buynow_LG.gif" border="0" name="submit" alt="PayPal - הדרך הקלה והבטוחה יותר לשלם באינטרנט!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>
</td>
            </tr>
            <tr>
              <td>10</td>
              <td><span dir="ltr">499.00</span> ש"ח</td>
              <td class="table-buy-column"><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="9PWC8RQXW9FPA">
<input type="image" src="https://www.paypalobjects.com/he_IL/i/btn/btn_buynow_LG.gif" border="0" name="submit" alt="PayPal - הדרך הקלה והבטוחה יותר לשלם באינטרנט!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>
</td>
            </tr>
            <tr>
              <td>20</td>
              <td><span dir="ltr">899.00</span> ש"ח</td>
              <td class="table-buy-column"><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="UGMJ8WHM4Z4UL">
<input type="image" src="https://www.paypalobjects.com/he_IL/i/btn/btn_buynow_LG.gif" border="0" name="submit" alt="PayPal - הדרך הקלה והבטוחה יותר לשלם באינטרנט!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>
</td>
            </tr>
           
          </tbody>
        </table>
      </div>
    </div>
    <div class="col-sm-5">
      <div class="panel panel-default payment-icons-panel">
        <%= image_tag "secure-payment.png", class: "img-responsive center-block" %>
      </div>
      <div class="panel panel-default panel-whats-included">
        <div class="panel-heading">
          <h2 class="headline headline-buy"><%= I18n.t "buy-barcodes.whats-included" %></h2>
        </div>


        <div class="included-item">
          <h3 class="included-item-title">
            UPC ו- EAN 
          </h3>
          <p></p>
          <%= image_tag "ean-and-upc-barcodes.png", class: "img-responsive center-block included-item-image" %>
        </div>

        <div class="included-item">
          <h3 class="included-item-title">
            תמונות ברקוד דיגיטלי ב- 3 פורמטים איכותיים - JPEG, TIFF ו- EPS
          </h3>
          <%= image_tag "image-formats.png", class: "img-responsive center-block included-item-image" %>
        </div>

        <div class="included-item">
          <h3 class="included-item-title">
             תעודת מקוריות +חשבונית
          </h3>
          <%= image_tag "invoice-and-certificate.png", class: "img-responsive center-block included-item-image" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/faq.html.erb
<div class="container">
  <h1 class="headline headline-faq">שאלות נפוצות</h1>

  <ul class="faq-summary-list">
    <% I18n.t("faqs").each_with_index do |faq, i| %>
      <li>
        <%= link_to faq[:question], "#faq-#{i + 1}", class: "faq-summary-list-link" %>
      </li>
    <% end %>
  </ul>

  <% I18n.t("faqs").each_with_index do |faq, i| %>
    <div class="faq-answer">
      <a class="anchor-offset" name="<%= "faq-#{i + 1}" %>"></a>
      <h2 class="sub-headline sub-headline-faq">
        <%= faq[:question] %>
      </h2>
      <p>
        <% faq[:answer].each do |paragraph| %>
          <p>
            <%= paragraph.html_safe %>
          </p>
        <% end %>
      </p>
    </div>
  <% end %>